#  _____        _                    _____  _                   
# |  __ \      (_)                  / ____|| |                  
# | |__) |_ __  _  _ __ ___    ___ | (___  | |__    ___   _ __  
# |  ___/| '__|| || '_ ` _ \  / _ \ \___ \ | '_ \  / _ \ | '_ \ 
# | |    | |   | || | | | | ||  __/ ____) || | | || (_) || |_) |
# |_|    |_|   |_||_| |_| |_| \___||_____/ |_| |_| \___/ | .__/ 
#                                                        | |    
#                                                        |_| 
version: 1.1
Save_Changes_every_X_Seconds: 60
SpamProtection_in_milliseconds: 60
Price_Linking:
  for_all_Items_DISABLED: false
  list_of_disabled_Items: []
Price_Calculation:
  dynamic_prices_for_all_Items_DISABLED: false
  globalRateOfInflation: 1.0
  value_every_item_bought_gets_multiplied_with: 1.0
  value_every_item_sold_gets_multiplied_with: 1.0
  taxValueItemIncreasesWhenItWasCrafted: 0.05
Appearance:
  allow_ESC_to_close_inventories: true
  Buy_Button: '35:5'
  Sell_Button: '35:14'
  Close_Button: '160:0'
  NPC_Button: '389:0'
  background_Item: '160:15'
  Sign_Shop_Headline: PrimeShop
